Added commands for docker and composer
php-etl/dockerfile pull request #9
Opened 2023-12-15 08:43 UTC by sebprt

2024-01-26 10:06 UTC, JoMessina approved these changes

2024-01-26 10:06 UTC, JoMessina approved these changes

2024-01-26 11:24 UTC, gplanchat requested changes

2024-01-26 11:24 UTC, gplanchat commented on src/Dockerfile/Arg.php
> +        return sprintf('ARG %s', $this->name);
Il manque la valeur par défaut de [`ARG`](https://docs.docker.com/engine/reference/builder/#arg)

2024-01-26 11:24 UTC, gplanchat commented on src/PHP/ComposerConfig.php
> +final readonly class ComposerConfig implements Dockerfile\LayerInterface, \Stringable
Si la config est globale, le nom de cette classe doit le faire transparaitre

2024-01-26 16:18 UTC, sebprt commented on src/Dockerfile/Arg.php
> +        return sprintf('ARG %s', $this->name);
C'est ajouté

2024-01-26 16:18 UTC, sebprt commented on src/PHP/ComposerConfig.php
> +final readonly class ComposerConfig implements Dockerfile\LayerInterface, \Stringable
C'est fait

2024-02-01 09:57 UTC, gplanchat requested changes

2024-02-01 09:57 UTC, gplanchat commented on src/Dockerfile/Arg.php
> +        private string $defaultValue,
La valeur par défaut peut être absente
```suggestion
        private ?string $defaultValue = null,
```

2024-02-01 09:57 UTC, gplanchat commented on src/Dockerfile/Arg.php
> +        return sprintf('ARG %s=%s', $this->name, $this->defaultValue);
La valeur par défaut peut être absente

```suggestion
        if ($this->defaultValue !== null) {
            return sprintf('ARG %s=%s', $this->name, $this->defaultValue);
        }
        return sprintf('ARG %s', $this->name);
```

2024-02-01 09:57 UTC, gplanchat commented on src/PHP/ComposerConfigGlobal.php
> +        private string $token,
Il faut prévoir d'utiliser un argument `ARG` pour ne pas avoir le token dans le Dockerfile et qu'il ne soit pas visible publiquement

2024-02-01 10:03 UTC, gplanchat requested changes

2024-02-01 10:03 UTC, gplanchat commented on src/PHP/ComposerConfigGlobal.php
> +        private string $token,
```suggestion
        private string $tokenArgument,
```

2024-02-01 10:03 UTC, gplanchat commented on src/PHP/ComposerConfigGlobal.php
> +        ));
```suggestion
        return (string) new Dockerfile\Run(<<<"RUN"
            composer config --global {$this->host} \${{$this->tokenArgument}}
            RUN,
        );
```

2024-02-01 10:05 UTC, gplanchat approved these changes

2024-02-15 09:03 UTC, merged